### ISSUE TITLE
People Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#1]
Initial requirements:
- The landing page of people page should include everybody
    - Each person thumbnail should be click-able (reference individual pages)
    - Divide by different job/degree titles (PI, PostDoc, PhD, RA, Masters, Bachelors, ...)
    - Include an alumni page
- Each person should  have its own page which they can control
    - Should include a bit more detailed background, links to projects involved and publication posts

To be discussed:
1) Do we keep alive the personal page of any alumni?
2) Should the person thumbnail pop-out a very short summary instead of individual pages? [1]
3) Should we include icon links to Google Scholar/Github/Person page/Twitter/Orchid/Email/LinkedIn? [2]
4) Should we have standardized profile shots? [3]

References:
1)  https://weblab.t.u-tokyo.ac.jp/en/members/
2)  https://weblab.t.u-tokyo.ac.jp/en/members/
3)  https://weblab.t.u-tokyo.ac.jp/en/members/

**Comment by Warvito** [comment]
Added draft of people page in 49654f8
