### ISSUE TITLE
Publications Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#2]
Initial requirements:
- Publications should be ordered chronologically.
- Each publication links to its own blog post
- Put the funding bodies at the bottom

To be discussed:
1) Do we break down our publications only by a year, or do we break them down by project, funders, researchers (maybe can be done with tags)? [1]
2) Should we break down our publications by Journal, Oral, Main Conference, Workshop, Abstract, Books, Invited Presentation/Lecture? [2]
3) Should each publication have "in-line" Harvard/IEEE/Bibtex citation? [3]

References:
1) http://www.vanderschaar-lab.com/NewWebsite/Publications.html
2) https://weblab.t.u-tokyo.ac.jp/en/publications/
3) https://biomedia.doc.ic.ac.uk/publications/

**Comment by Warvito** [comment]
### Discussion from 23/04/2020 meeting group
Actions
- [x] Title, authors, and DOI similar to [1]
- [x] Add years similar to [2]

References
[1] - https://biomedia.doc.ic.ac.uk/publications/
[2] - https://mmistakes.github.io/minimal-mistakes/year-archive/
