### ISSUE TITLE
Personal Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#3]
Initial requirements:
- Name and Photo
- Links to personal social media (LinkedIn/Twitter), GitHub and KCL E-mail 
- Position (PI/RA/PostDoc/PhD/Masters/Bachelors)
- Address where the person is found 
- Main funding body
- List of projects in which the person is a collaborator
- List of publications

To be discussed:
1) N/A

References:
1) N/A

**Comment by Warvito** [comment]
### Discussion from 23/04/2020 group meeting
Actions:
- [x] Delete funding section
- [x] Present the latest 5 publication
- [x] Add Sidebar for each people - similar to [1] but email should be in the top, add orchid and pure, pin these other fields like [2] and tell Paul, add Projects.
- [x] Add Schema with the values from the frontmatter [3].
- [x] Fix Projects section
- [x] Add a HTML/Javascript (visualization) inside the .md [4]

References:
[1] - https://mlmh-lab.github.io/members/Walter/
[2] - https://github.com/AmigoLab/amigolab.github.io/blob/master/_includes/author-profile.html
[3] - https://schema.org/
[4] - https://kramdown.gettalong.org/syntax.html#html-blocks

**Comment by Warvito** [comment]
Schema check example
[https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Famigolab.github.io%2Fpeople%2Fwalter_pinaya%2F](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Famigolab.github.io%2Fpeople%2Fwalter_pinaya%2F)
