### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#4]
Initial requirements:
- Should include funders
- Create initial placeholder page
- To be detailed by @mjorgecardoso 

To be discussed:
1) Should we have something similar to van der Schaar and BioMedIA' website? [1][2]
2) Where do we put the funders since they facilitate the project all around?

References:
1) http://www.vanderschaar-lab.com/NewWebsite/index.html
2) https://biomedia.doc.ic.ac.uk/projects/

**Comment by Warvito** [comment]
### Discussion from 23/04/2020 meeting group
Actions
- [x] Add funders in the same page and showing all of them withouth scrolling down (horizontal desing).
- [x]  Show  grid as people page (image + name)

**Comment by danieltudosiu** [comment]
@virginiafdez What should be the sizes of the Project Logos and Founder Logos? People Portraits are 300x300pix.

**Comment by danieltudosiu** [comment]
@mjorgecardoso Please create the projects that this team researches so we can fill in that section on each person.
