### ISSUE TITLE
Publication Blog Post Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#5]
Initial requirements:
- At the top have the title, authors and publication venue
- Include full BibTeX reference at the bottom of it (Github style) [1]
- Be able to run visualization in-line 
- Have tags so it can be sorted by Project, Funders, Authors, Year
- Link to the published version (ideally not ArXiv)
- Should have the funders at the bottom

To be discussed:
1) Should we include the Abstract for SEO? [2]

References:
1)  https://github.com/danieltudosiu/nmpevqvae
2) https://mlmh-lab.github.io/publications/2017-06-01-/

**Comment by Warvito** [comment]
### Discussion from 23/04/2020
Action
- [x] Add sidebar from Author
- [x] Enable javascript inside .md file

**Comment by Warvito** [comment]
Discussion from 05/05/2020
Action
- [x] Remove sidebar from Author
- [x] Enable javascript inside .md file
