### ISSUE TITLE
Education Page

### ISSUE THREAD

**Issue by danieltudosiu** [AmigoLab/amigolab.github.io#9]
Initial Requirements:
- Have a chronologically (by year and trimester) ordered list of courses taught by members of the group [1] [2]
- Each course should have a small description, link to KEATS/KCL and list of recommended readings [1] [2]
- Should be grouped by the lead lecturer [2]

To be discussed:
- N/A

References:
1) http://engineering.nyu.edu/microbioengineering/teaching.html
2) http://svl.stanford.edu/teaching/

**Comment by Warvito** [comment]
### Discussion from 23/04/2020 meeting group
- [ ] Add Schema
- [ ] Add years in the top
